### ISSUE TITLE
Card.io interface appears, camera not working though.

### ISSUE THREAD

**Issue by sjmeyer** [card-io/card.io-Cordova-Plugin#50]
### Required Information

- Cordova Version: 6.3.1
- Plugin Version: 2.1.0
- Platforms: iOS
- Device OS Version and Device: iOS 10.0 on iPhone 6s Plus

### Issue Description
The canScan function returns "true" and the Card.io interface pops up when I tap the scan button, but the camera seems to be disabled because it doesn't work. I've tried setting the noCamera option to false, but it doesn't seem to fix the issue. Other options like the hideCardIOLogo : false works.

The Card.io interface shows the block where the camera view is supposed to be, the "Cancel" button, and the "Enter Manual" button. Neither of the buttons work though. If I check the logs in Xcode an error message appears the moment I take the Scan button. The error: shows a bunch of gibberish codes and at the end of the line "Thread : signalSIGABRT

Any ideas of what could be wrong? Do I have to enable the camera? (I never got a pop-up asking to allow camera usage) Do I have to add the camera plugin?

canScan return:
![img_0454](https://cloud.githubusercontent.com/assets/8191390/19029838/e0c1976a-8949-11e6-9ed3-1601b2cdc24d.PNG)

Card.io interface:
![img_0455](https://cloud.githubusercontent.com/assets/8191390/19029854/0a997364-894a-11e6-8d8d-04a3eccc1952.PNG)

Xcode logs:
![xcode](https://cloud.githubusercontent.com/assets/8191390/19029915/912270c0-894a-11e6-9d9b-218663f725e5.png)

**Comment by bluk** [comment]
Do you have the `NSCameraUsageDescription` set? See https://github.com/card-io/card.io-iOS-SDK/issues/209 .

**Comment by sjmeyer** [comment]
@bluk No I don't. How would I go about setting this? Where is the info.plist file in question?

**Comment by bluk** [comment]
@sjmeyer Depends on your build settings, but I would find and open the `<yourproject>.xcodeproj` in Xcode and edit your Info.plist settings via Xcode. Or you can find a `*Info.plist` file in your project and try to edit that manually by adding:

```
	<key>NSCameraUsageDescription</key>
	<string>To scan credit cards.</string>
```
inside the main `dict` element. It should be in a subdirectory inside your Cordova project.

**Comment by sjmeyer** [comment]
@bluk Thanks, it worked. Closing this issue now.
