### ISSUE TITLE
"plugin_not_install" error message on Ionic2

### ISSUE THREAD

**Issue by CHOMNANP** [card-io/card.io-Cordova-Plugin#53]
### Required Information

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v5.10.1
Xcode version: Not installed

- Platforms iOS and Android
- Device OS Version and Device Nexus 5x

### Issue Description

I have tried this in Ionic.

- ionic start myapp tabs --v2
- cd myapp
- ionic plateform add android
- ionic plugin add https://github.com/card-io/card.io-Cordova-Plugin
- add the code block bellow to my controller
`import { CardIO } from 'ionic-native';

CardIO.canScan()
  .then(
    (res: boolean) => {
      if(res){
        let options = {
          requireExpiry: true,
          requireCCV: false,
          requirePostalCode: false
        };
        CardIO.scan(options);
      }
    }
  );`

The message that I got from my mobile phone is "plugin_not_install".
Not sure what I do wrong.

I tried the same method with other plugin like "Camera", and it works fine.

Thanks,
Punleu

**Comment by CHOMNANP** [comment]
These are my system information.
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v5.10.1
Xcode version: Not installed

**Comment by nakulgulati** [comment]
@CHOMNANP I was able to replicate the issue by calling CardIO functionality before `deviceready` has been fired. 

Try calling CardIO functionality after `platform.ready()` has been resolved.

**Comment by CHOMNANP** [comment]
I just got this fix by our awesome friend in https://ionic-worldwide.slack.com
I got the error because I test CardIO in Ionic View. I got it fix by building the APK for the project, then install the APK on the device.

So Ionic View didn't support this plugin yet.

Thanks,
Punleu
