### ISSUE TITLE
cordova plugin issue - credit card scan didn't complete

### ISSUE THREAD

**Issue by yoavpa** [card-io/card.io-Cordova-Plugin#57]
### Required Information

- Cordova Plugin Version: card.io.cordova.mobilesdk 2.1.0
- Platforms (iOS/Android/Both): ios 10.x
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.):

### Issue Description

Hi,
I  followed all the instruction steps, installed the cordova plugin card.io and made a sample project as 
described in  [ https://github.com/card-io/card.io-Cordova-Plugin](https://github.com/card-io/card.io-Cordova-Plugin) - **Sample HTML + JS** 
Then, i tried to scan a credit card  image.
The Camera started to scan the image.
However, the scanning didn't complete and it didn't reach to the callback onCardIOComplete.
Instead, it continue to display the scanning screen.

Please assist
Thanks,
Yoav

**Comment by ghost** [comment]
I am getting same issue what is the solution
